rostools/github-intro

.github/CODEOWNERS
Adds the codeowners file so we get assigned as reviewers.
=> chore: :technologist: add `CODEOWNERS`

LICENSE.md
Updates the license to use CC-BY, not MIT (which is for code).
=> docs: :page_facing_up: update to CC-BY License

_publish.yml, _quarto.yml
This PR adds connections to Netlify to build the website, plus changes the title on the website
=> build: :wrench: update Quarto config settings to build website

preamble/pre-course.qmd, preamble/schedule.qmd, preamble/syllabus.qmd, sessions/introduction.qmd, sessions/lesson.qmd
=> fix: :adhesive_bandage: change includes wip to text_snippet

preamble/schedule.qmd, sessions/basics.qmd, sessions/conclusion.qmd, sessions/using-issues.qmd, sessions/what-next.qmd, sessions/working-with-files.qmd
Adds multiple session files to match our agreed on schedule
Closes #28
=> chore(sessions): :truck: add or rename session files to match schedule

_quarto.yml, preamble/pre-course.qmd
Small fixes to get the website to build correctly on GitHub.
=> build: :fix: fix issues with website build workflow

sessions/basics.qmd
Add a priming discussion activity.
Related to #36
=> docs(sessions): :memo: add starting discussion activity to prime them

includes/_basics-objectives.qmd, includes/_using-issues-objectives.qmd, includes/_working-with-files-objectives.qmd, preamble/syllabus.qmd, sessions/basics.qmd, sessions/using-issues.qmd, sessions/working-with-files.qmd
=> docs(preamble): :memo: add learning objectives

appendix/for-instructors.qmd
This PR simplifies the checklist a bit, updates it based on discussions, and adds the stickies/hat item to it.
Closes #47
=> docs(appendix): :memo: add to-do item related to post-it notes

_publish.yml, _quarto.yml
Renamed repo to simply `github-intro`.
Doesn't need a review.
=> build: :wrench: update URLs to `github-intro`

sessions/working-with-files.qmd
=> docs(sessions): :memo: discussion to connect work with learning GitHub

sessions/basics.qmd
=> docs(sessions): :memo: discussion on explaining basics of Git to neighbour

sessions/using-issues.qmd
=> docs(sessions): :memo: discussion on using Issues in work

sessions/working-with-files.qmd
=> docs: :memo: add section on file and folder naming

appendix/for-instructors.qmd
… to only be to check that leaners has sent their usernames. 
This might be controversial 🤔 
=> docs: :memo: update pre-workshop tasks

includes/_working-with-files-objectives.qmd, sessions/working-with-files.qmd
This PR adds/updates the learning objectives section of `working-with-files`.
=> docs: add learning objectives section to `working-with-files`

includes/_working-with-files-objectives.qmd, sessions/working-with-files.qmd
This PR updates the reading task section of the “Working with files” session.
=> docs: :memo: update reading task section of `working-with-files`

sessions/basics.qmd
=> docs(sessions): :memo: add section on file paths

includes/_working-with-files-objectives.qmd, sessions/working-with-files.qmd
This PR adds a code along that adds the first file (a tomato soup recipe) to “Working with files”.
=> docs: add code along with the first recipe to `working-with-files`

preamble/syllabus.qmd
=> docs: :memo: minor updates to syllabus section

sessions/working-with-files.qmd
The end of this sentence (and section) might’ve been removed in a merge at some point or might never have existed 🤷‍♀️  Either way: Here it is! 
=> docs: ✏️ add missing end to sentence in “Exploring the history"

sessions/using-issues.qmd
=> docs: :pencil2: Issue --> issue

includes/_using-issues-objectives.qmd, preamble/syllabus.qmd
“Issue" --> “issue" or “Issue" --> "GitHub Issue"
This PR doesn’t need a review.
=> docs: :pencil2: remove capitalisation of “issue"

sessions/using-issues.qmd
This setup aligns with this section in the "Working with files” session. It also removes the “TODO: Session” section. I’ll add the coming sections in another PR. 
=> docs: :memo: update learning objectives section in Issues session

sessions/using-issues.qmd
I thought it would make sense to create the first issue together. However, I’m not sure we’ll return to adding a `sweets/` folder, so this might be a bit random? Thoughts? 🤔 
Together with #92, this PR closes #84 
=> docs: :memo: add type along section that creates the first issue

sessions/using-issues.qmd
Where learners will also tag their neighbour.
=> docs: :memo: update create issue exercise to be a discussion issue

images/icon-ellipsis.svg, sessions/using-issues.qmd
This PR adds a callout tip on how to edit issues and comments.
=> docs: :memo: add tip on how to edit issues and comments

appendix/for-instructors.qmd
=> chore: :bento: instructors should disable browser extensions before the workshop

preamble/pre-workshop.qmd
Closes #100 
Any other notification settings they should edit?
=> feat: :sparkles: add section on email notifications

.typos.toml, .vscode/settings.json, justfile
Matching what was done in Seedcase. Adding spell checker.
=> build: :hammer: add spell checking to justfile

index.qmd
=> fix: :pencil2: "course" -> “workshop” in `index.qmd`

.vscode/json.code-snippets, README.md, _extensions/rostools/r3-theme/text-snippet.lua, _quarto.yml, appendix/for-teachers.qmd, index.qmd, sessions/basics.qmd, sessions/using-issues.qmd
To align on teaching rather than instructing
=> refactor: :recycle: edit instruct to teach

overview/learning-design.qmd
This PR adds the learning design from the r3-theme.
This PR needs no review.
=> feat: :sparkles: add learning design from r3-theme

index.qmd
Read through the landing page and made some minor adjustments. 
=> refactor: minor changes to landing page content

pre-workshop/code-of-conduct.qmd
=> feat(preamble): :sparkles: include code of conduct

_quarto.yml, pre-workshop/index.qmd
=> refactor(sessions): :recycle: simplify headers to keep sidebar cleaner

pre-workshop/index.qmd
Minor edits from reading through this page.
=> refactor: :recycle: minor edits to pre-workshop overview

pre-workshop/github-account.qmd
=> refactor: ♻️ review of GitHub account section

pre-workshop/pre-survey.qmd
=> feat(preamble): :sparkles: add pre-workshop survey link

sessions/introduction.qmd
=> feat(sessions): :sparkles: finish big picture

sessions/conclusion.qmd
Related to what the instructors of the intermediate R workshop talked about during the debrief. Having the survey be clearly indicated.
=> feat(sessions): :sparkles: add survey button to end of workshop

overview/syllabus.qmd
=> fix(preamble): :pencil2: edits to syllabus page

pre-workshop/pre-survey.qmd
=> fix(preamble): :pencil2: convert link to survey to be a button

sessions/introduction.qmd
=> fix(sessions): :pencil2: minor change to note about origami hats for help

.vscode/settings.json
=> chore: :technologist: update conventional commit scopes to fit folder structure

includes/_git-basics.qmd
=> fix(preamble): :pencil2: edits to Git basics section

_quarto.yml, appendix/references.qmd
=> chore: :fire: remove leftover/unused references file

sessions/conclusion.qmd
=> fix(sessions): :pencil2: edits to the conclusion session

_variables.yml, sessions/basics.qmd, sessions/using-issues.qmd
Also moved the icons into the `_variables.yml` file so they can be used in the issues session.
=> fix(sessions): :pencil2: edits to using issues session

sessions/working-with-files.qmd
=> fix(sessions): :pencil2: edits to working with files session

sessions/using-issues.qmd
I think we agreed to remove this right?
=> refactor(sessions): :fire: remove leftover collaboration section

includes/_git-basics.qmd
=> fix(includes): :pencil2: minor text edits to `_git_basics.qmd`

includes/_github-basics.qmd
=> refactor(includes): :pencil2: minor text edits to `_github-basics.qmd`

overview/schedule.qmd
=> docs: :memo: add todo on updating schedule minutes

includes/_git-basics.qmd, sessions/basics.qmd
=> refactor: :recycle: minor text edits to basics session

sessions/introduction.qmd
This PR DESCRIBE CHANGES.
Closes #
This PR needs a quick/an in-depth review.
=> Fix two typos in 10.1 and 10.2

.vscode/settings.json
=> chore: :technologist: add "includes" to conventional scopes

sessions/basics.qmd
=> fix: :pencil2: typos in basics of Git

_quarto.yml
To merge once we're all done :tada:
=> build: :wrench: remove "wip" status from `_quarto.yml`

overview/is-this-for-you.qmd, overview/syllabus.qmd
This PR fixes some more typos in other sections.
=> fix: :adhesive_bandage: fix some typos

includes/objectives/_working-with-files.qmd, sessions/working-with-files.qmd
This PR makes minor edits to the objectives and the session itself.
This PR needs no review.
=> fix: :pencil2: minor edits to working with files

includes/_git-basics.qmd, includes/objectives/_using-issues.qmd, includes/objectives/_working-with-files.qmd, sessions/introduction.qmd, sessions/working-with-files.qmd
=> fix(sessions): :pencil2: some small edits while reviewing

.github/workflows/add-to-project.yml, .github/workflows/build-website.yml
=> ci: :lock: improve security of workflows via the template

.cz.toml, .github/workflows/release-project.yml, CHANGELOG.md
=> ci: :construction_worker: add auto release workflow

tools/get-contributors.sh
=> build: :hammer: add contributor list script

.github/pull_request_template.md
=> chore: :technologist: add PR template

.pre-commit-config.yaml
=> build: :wrench: add gitleaks pre-commit hooks, plus upgrade versions

includes/objectives/_basics.qmd, includes/objectives/_using-issues.qmd, overview/is-this-for-you.qmd, overview/schedule.qmd, overview/syllabus.qmd
=> refactor: ♻️ minor text edits in overview section

includes/_git-basics.qmd, includes/_github-basics.qmd, pre-workshop/git-and-github.qmd, pre-workshop/github-account.qmd, pre-workshop/overview.qmd, pre-workshop/survey.qmd
=> refactor(sessions): ♻️ minor text edits to Pre-workshop section

CHANGELOG.md
The original one was too much targeted to software, so I expanded this description.
=> docs: :memo: describe in more detail how releases work

includes/objectives/_create-repo.qmd, sessions/create-repo.qmd
Adds a section walking through the landing page.
Closes #200
=> feat(sessions): :sparkles: add walkthrough of repository landing page

includes/objectives/_using-issues.qmd
=> refactor: :pencil2: minor fix in issues objectives

sessions/working-with-files.qmd
Minor changes from going through the session.
=> refactor: ♻️ minor changes to working with files

sessions/working-with-files.qmd
=> feat(sessions): :sparkles: walkthrough of the file tree sidebar

sessions/using-issues.qmd
=> fix: :pencil2: update creating an issue type-along to not mention now removed decision
