_quarto.yml, index.qmd, preamble/pre-course.qmd, preamble/schedule.qmd, preamble/syllabus.qmd, sessions/introduction.qmd, sessions/lesson.qmd, sessions/what-next.qmd
This PR adds the wip `text_snippet` to `_quarto.yml` and removes it from the individual docs. 
Closes #25 
=> refactor: :recycle: move wip `text_snippet` to config

appendix/for-instructors.qmd
This PR adds a list of pre-tutorial tasks for instructors.
Closes #7 
=> docs: :memo: add pre-tutorial tasks for instructors

preamble/syllabus.qmd
=> docs(preamble): :memo: add the assumptions and "who you are" section

LICENSE.md, README.md, _quarto.yml, appendix/for-instructors.qmd, preamble/syllabus.qmd, sessions/basics.qmd, sessions/introduction.qmd, slides/introduction.qmd
Since we agreed to move away from "tutorial" to avoid confusing it with diátaxis's more technical/non-interactive definition of tutorials
Q: Should we rename the repo and url as well? For now, I kept it as is.
Closes #44 
=> docs: :pencil2: "tutorial" -> "workshop"

sessions/lesson.qmd, sessions/using-issues.qmd, sessions/working-with-files.qmd
This PR adds exercises.
Related to #10 
=> docs: :memo: add exercises

sessions/working-with-files.qmd
This PR adds a code along that deletes a the tomato soup file and the `soups/` folder.
=> docs: :memo: add code along that deletes a the tomato soup file and folder

sessions/working-with-files.qmd
This PR updates the exercise that renames and moves the cookie recipe so it also edits the content of the file - along with other minor updates.
=> docs(sessions): :memo: update "edit cookie recipe" exercise

sessions/working-with-files.qmd
This PR adds a summary section to the “Working with files” session.
Closes #60 
=> docs(sessions): :memo: add summary section

preamble/schedule.qmd, preamble/syllabus.qmd
Just add some times to the schedule, plus state how long the workshop is.
Closes #29
=> docs(preamble): :memo: add times to schedule and how long it is

sessions/working-with-files.qmd
This add section on exploring the history and adds some minor edits to the exercise about finding a specific commit.
=> docs: add section on exploring the history

README.md
Updates the README text of the repo.
Closes #41
=> docs: :memo: update the README file

index.qmd
This PR adds content for the landing page.
Closes #53
=> docs: :memo: add content to website landing page

sessions/using-issues.qmd
Since they have tagged their neighbour in the previous exercise, I thought it would be a good idea to add a short section on how to navigate the notifications on GitHub.
Actually also related to #84 
=> docs: :memo: add type-along on GitHub notifications

sessions/using-issues.qmd
This PR adds a summary section to the issues session. This might need to change based on the other PRs related to this session. 
Closes #62 (bc it’s the last part of this session).
=> docs: :memo: add summary section to issues session

sessions/conclusion.qmd, sessions/working-with-files.qmd
This PR adds some concluding remarks, mostly summarising what we’ve done throughout the workshop + a what’s next section with links to other `rostools` workshops. I’ve added a TODO on adding more big picture content, bc I thought it would make sense to wait until the introductory bigger picture has been made; then this conclusion can recap some of that.
I’ve also moved the discussion activity on how they can use GitHub in their own projects to this session. Since they will know about issues and contributors as well at this point (as opposed to in the Working with files session), I thought it might be nice to move it to the end of the workshop. But if you disagree, we can revert that commit.
Closes #80 
=> feat: ✨ add concluding remarks

includes/objectives/_basics.qmd, index.qmd, preamble/pre-workshop.qmd, preamble/schedule.qmd, preamble/syllabus.qmd
This is mostly minor rephrasings ✏️  
The last two commits are about styling of the lists. I removed empty lines between the bullet points to they are then rendered closer together. However, for the includes that are right after each other, I *think* the blank line at the end of each of them makes Quarto render them with blank lines between them. As a potential fix, I divided the objectives into the learning outcomes of each session. 
I’m not sure I particularly like this fix, but I couldn’t find a way to render them as one collected list without the blank lines in between. Thoughts? 😬 
Annoying blank lines look like this: 
What I want is this (ideally without each includes in its own section - but maybe it isn’t too bad?): 
=> refactor: ♻️ minor rephrasings and styling on landing page and in preamble

includes/_git-basics.qmd, includes/_github-basics.qmd, pre-workshop/git-and-github.qmd, pre-workshop/pre-survey.qmd
=> refactor: ♻️ review of Git and GitHub section

LICENSE.md
So it doesn’t say “License License”.
=> fix: remove duplicate "license"

sessions/basics.qmd
This PR simplifies and shortens the callout note, based on feedback from @K-Beicher that the callout note was quite a "block" of text. That feedback was mostly about the layout, but I thought we could simplify the text as well, since it was a bit wordy.
=> refactor(sessions): :recycle: simplify callout note on vc and git reading repetition

pre-workshop/github-account.qmd
Needs to use `https:`
No review needed.
=> fix: :pencil2: fix URL to point to GitHub

overview/schedule.qmd
This PR updates the session duration and removes the TODO item for that.
This PR needs no review.
=> fix: :pencil2: update session minutes

justfile
Ignore these (non-essential/only temp) dirs when listing TODOs.
No review needed.
=> build: :hammer: ignore more dirs when listing todos

_variables.yml, sessions/working-with-files.qmd
This removes the sections on "copying" the recipes, instead writing them out. They are also shorter now. Also simplifies and shortens other sentences and paragraphs related to this change.
Closes #196
=> refactor(sessions): :recycle: shorten recipes and simplify add/edit file section

sessions/using-issues.qmd
=> refactor: ♻️ simplify what are GitHub issues section
